version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Nginx serves on 80, mapped to localhost:3000
    volumes:
      - ./frontend:/app
    restart: always
